export const words = [
  "Stay Curious.",
  "Read More.",
  "Unleash Wonder",
  "Curious Pursuit",
  "Explore More",
  "Seek Knowledge",
  "Wonder Wildly",
  "Question Everything",
  "Ignite Curiosity",
  "Discover Joy",
  "Embrace Exploration",
  "Curiosity Thrives",
  "Nurture Wonder",
  "Fuel Discovery",
  "Spark Learning",
  "Inquire Within",
  //   "Adventurous Minds",
];
